const express = require('express')
const router = express.Router();
const {getVocabLesson, getVocabinLesson, getVocabs, setAlarmVocab, getAlarmVocab, updateAlarmVocab, addVocab, addVocabLesson, updateTopic, deleteTopic,updateVocab,deleteVocab} = require('../controllers/Vocab')
const {setUserInfo, updateUser, getAllUsers, getUserData,updateUserPrivate} = require ('../controllers/User')
const {uploadAudio, uploadPracticeHistory} = require ('../controllers/SWskills')
const {getQuestion, pushPracticeHistory, getOneQuestion, addQuestion, countQuestion, getAllQuestion, updateQuestion, deleteQuestion, getReviewQuestion, getSavedQuestion, updateSavedQ} = require('../controllers/Question')
const {uploadPracticePlan, getPracticePlan, updatePracticePlan} = require('../controllers/PracticePlan')
const {addPost, updatePost, addComment, getOneComment, addNotification, deleteNotification, updateNotification,
     filterOnlyPost,filterOnlyhashtag,filterBoth, pushSavedPost, getSavedPost, deletePost, getPosts}=require('../controllers/Post')
const {addTest, getAllTest, updateTest, deleteTest, uploadTestHistory} = require('../controllers/Test')

//vocab
router.get('/VocabLessons',getVocabLesson)
router.get('/VocabinLesson/:TopicId',getVocabinLesson)
router.get('/Vocabs',getVocabs)
router.get('/getAlarmVocab/:userId',getAlarmVocab)
router.post('/alarmVocab/:userId',setAlarmVocab)
router.put('/updateAlarmVocab/:userId', updateAlarmVocab)
//user
router.put('/setUserInfo/:userId', setUserInfo)
router.put('/updateUser/:userId', updateUser)
router.put('/updateUserPrivate/:userId', updateUserPrivate)
router.get('/Users', getAllUsers)
router.get('/UserData/:userId', getUserData)
//question
router.get('/Question/:Part/:userId/:number',getQuestion)
router.post('/PracticeHistory/:userId/:sign',pushPracticeHistory)
router.get('/oneQuestion/:Part/:Qid',getOneQuestion)
router.post('/Question/:Part/add',addQuestion)
router.get('/countQuestion/:Part',countQuestion)
router.get('/getAllQuestion/:Part',getAllQuestion)
router.put('/updateQuestion/:Part/:Qid', updateQuestion)
router.delete('/deleteQuestion/:Part/:Qid',deleteQuestion)
router.post('/ReviewQuestion',getReviewQuestion)
router.get('/getSavedQuestion/:userId',getSavedQuestion)
router.put('/updateSavedQuestion/:userId', updateSavedQ)
router.post('/uploadAudio', uploadAudio)
router.post('/uploadPracticeHistory', uploadPracticeHistory)
//PracticePlan
router.post('/PracticePlan/:userId/add', uploadPracticePlan)
router.get('/PracticePlan/:userId', getPracticePlan)
router.put('/PracticePlan/:userId/update', updatePracticePlan)
//post
router.post('/addPost', addPost)
router.put('/updatePost/:postId', updatePost)
router.post('/addComment/:sign/:momId', addComment)
router.post('/addNotification', addNotification)
router.get('/getoneComment/:commentId',getOneComment)
router.delete('/deleteNoti/:notiId',deleteNotification)
router.put('/updateNoti/:notiId', updateNotification)
router.get('/filterOnlyhashtag/:hashtag',filterOnlyhashtag)
router.get('/filterOnlyPost/:userId/:type',filterOnlyPost)
router.get('/filterBoth/:userId/:type/:hashtag',filterBoth)
router.put('/savePost/:userId/:postId', pushSavedPost)
router.get('/getsavePost/:userId',getSavedPost)
router.delete('/deletePost/:postId',deletePost)
router.get('/getPosts',getPosts)
//addvocab
router.post('/addVocabLesson', addVocabLesson)
router.post('/addVocab', addVocab)
router.delete('/deleteTopic/:topicId', deleteTopic)
router.delete('/deleteVocab/:vocabId', deleteVocab)
router.put('/updateVocab/:vocabId', updateVocab)
router.put('/updateTopic/:topicId', updateTopic)
//test
router.post('/Test/add', addTest)
router.get('/Tests', getAllTest)
router.put('/Test/update/:testId', updateTest)
router.delete('/Test/delete/:testId', deleteTest)
router.post('/Test/TestHistory/:userId/upload', uploadTestHistory)
module.exports = router